// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Database
{
    public partial class Cards
    {
        public Cards()
        {
            Save = new HashSet<Save>();
        }

        public int Id { get; set; }
        public string Color { get; set; }
        public int Number { get; set; }

        public virtual ICollection<Save> Save { get; set; }
    }
}