// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Database
{
    public partial class GameUser
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int GameId { get; set; }
        public int HandIndex { get; set; }

        public virtual Game Game { get; set; }
        public virtual Users User { get; set; }
    }
}