// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Database
{
    public partial class Users
    {
        public Users()
        {
            GameUser = new HashSet<GameUser>();
        }

        public int Id { get; set; }
        public string Username { get; set; }

        public virtual ICollection<GameUser> GameUser { get; set; }
    }
}