// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Database.Models
{
    public partial class Game
    {
        public Game()
        {
            Save = new HashSet<Save>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime Start { get; set; }

        public virtual ICollection<Save> Save { get; set; }
    }
}